version: "3"
services:
  minio:
    image: minio/minio:RELEASE.2020-04-04T05-39-31Z
    environment:
      - "MINIO_ACCESS_KEY=minio"
      - "MINIO_SECRET_KEY=minio123"
      - "MINIO_BROWSER=off"
    command: server /data
    ports:
      - "80:9000"
  gateway:
    image: minio/minio:RELEASE.2020-04-04T05-39-31Z
    command: gateway s3 http://minio:9000
    ports:
      - "9000:9000"
    environment:
      - "MINIO_ACCESS_KEY=minio"
      - "MINIO_SECRET_KEY=minio123"
  app:
    image: dalongrong/s3-fs:1.86
    privileged: true
    environment:
      - "AWS_KEY=minio"
      - "AWS_SECRET_KEY=minio123"
      - "S3_REGION=us-east-1"
      - "S3_URL=http://minio:9000"
      - "S3_BUCKET=apps"
    volumes: 
    - "./s3:/var/s3"